In [15]:
import numpy as np 
x=np.arange(0,11,1)
y=np.sqrt(x)
print(x+5)
print(x*2)
print(x**2)
print(y,y.dtype)


[ 5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766] float64


In [20]:
x=np.linspace(0, 2 * np.pi, 9)
y=np.sin(x)
print(x)
print(y)
sublistfirst= x[:3]
sublistmid= x[3:6]
sublistlast= x[6:9]
print(sublistfirst)
print(sublistlast)
print(sublistmid)

[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]
[0.         0.78539816 1.57079633]
[4.71238898 5.49778714 6.28318531]
[2.35619449 3.14159265 3.92699082]


In [49]:
rng = np.random.default_rng(seed=0)
normal_sample_mean_5 = rng.normal(loc=5, scale=2, size=200)
#print(normal_sample_mean_5)
def count_above(arr, threshold):
    v=0
    for idx in arr:
        if (idx > threshold):
           v=v+1
    return v       
v=count_above(normal_sample_mean_5, 4)
print(v)

k=np.sum(normal_sample_mean_5 > 4)
print(k)

140
140
